### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by YangNaruto** [jiamings/markov-chain-gan#3]
Why the following error?

Traceback (most recent call last):
  File "F:/ProjectPy/GAN/MC_GAN/mgan.py", line 35, in <module>
    trainer = Trainer(transition_fn, discriminator, data_sampler, noise_sampler, args.b, args.m)
  File "F:\ProjectPy\GAN\MC_GAN\train\wgan_gradient_penalty.py", line 11, in __init__
    self.transition_cell = TransitionCell(transition_fn)
  File "F:\ProjectPy\GAN\MC_GAN\utils\base.py", line 73, in __init__
    self.name = transition_fn.name
AttributeError: can't set attribute

**Comment by jiamings** [comment]
Your transition function does not have name attribute? Just set one for scoping purposes.
